from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(501, 509)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_11.setSpacing(5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_0.sizePolicy().hasHeightForWidth())
        self.btn_0.setSizePolicy(sizePolicy)
        self.btn_0.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_0.setObjectName("btn_0")
        self.gridLayout.addWidget(self.btn_0, 0, 0, 1, 1)
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_1.sizePolicy().hasHeightForWidth())
        self.btn_1.setSizePolicy(sizePolicy)
        self.btn_1.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_1.setObjectName("btn_1")
        self.gridLayout.addWidget(self.btn_1, 0, 1, 1, 1)
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_2.sizePolicy().hasHeightForWidth())
        self.btn_2.setSizePolicy(sizePolicy)
        self.btn_2.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_2.setObjectName("btn_2")
        self.gridLayout.addWidget(self.btn_2, 0, 2, 1, 1)
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_3.sizePolicy().hasHeightForWidth())
        self.btn_3.setSizePolicy(sizePolicy)
        self.btn_3.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_3.setObjectName("btn_3")
        self.gridLayout.addWidget(self.btn_3, 1, 0, 1, 1)
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_4.sizePolicy().hasHeightForWidth())
        self.btn_4.setSizePolicy(sizePolicy)
        self.btn_4.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_4.setObjectName("btn_4")
        self.gridLayout.addWidget(self.btn_4, 1, 1, 1, 1)
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_5.sizePolicy().hasHeightForWidth())
        self.btn_5.setSizePolicy(sizePolicy)
        self.btn_5.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_5.setObjectName("btn_5")
        self.gridLayout.addWidget(self.btn_5, 1, 2, 1, 1)
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_6.sizePolicy().hasHeightForWidth())
        self.btn_6.setSizePolicy(sizePolicy)
        self.btn_6.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_6.setObjectName("btn_6")
        self.gridLayout.addWidget(self.btn_6, 2, 0, 1, 1)
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_7.sizePolicy().hasHeightForWidth())
        self.btn_7.setSizePolicy(sizePolicy)
        self.btn_7.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_7.setObjectName("btn_7")
        self.gridLayout.addWidget(self.btn_7, 2, 1, 1, 1)
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_8.sizePolicy().hasHeightForWidth())
        self.btn_8.setSizePolicy(sizePolicy)
        self.btn_8.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_8.setObjectName("btn_8")
        self.gridLayout.addWidget(self.btn_8, 2, 2, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_9.sizePolicy().hasHeightForWidth())
        self.btn_9.setSizePolicy(sizePolicy)
        self.btn_9.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_9.setObjectName("btn_9")
        self.gridLayout_2.addWidget(self.btn_9, 0, 0, 1, 1)
        self.btn_11 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_11.sizePolicy().hasHeightForWidth())
        self.btn_11.setSizePolicy(sizePolicy)
        self.btn_11.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_11.setObjectName("btn_11")
        self.gridLayout_2.addWidget(self.btn_11, 0, 2, 1, 1)
        self.btn_12 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_12.sizePolicy().hasHeightForWidth())
        self.btn_12.setSizePolicy(sizePolicy)
        self.btn_12.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_12.setObjectName("btn_12")
        self.gridLayout_2.addWidget(self.btn_12, 1, 0, 1, 1)
        self.btn_13 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_13.sizePolicy().hasHeightForWidth())
        self.btn_13.setSizePolicy(sizePolicy)
        self.btn_13.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_13.setObjectName("btn_13")
        self.gridLayout_2.addWidget(self.btn_13, 1, 1, 1, 1)
        self.btn_14 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_14.sizePolicy().hasHeightForWidth())
        self.btn_14.setSizePolicy(sizePolicy)
        self.btn_14.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_14.setObjectName("btn_14")
        self.gridLayout_2.addWidget(self.btn_14, 1, 2, 1, 1)
        self.btn_15 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_15.sizePolicy().hasHeightForWidth())
        self.btn_15.setSizePolicy(sizePolicy)
        self.btn_15.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_15.setObjectName("btn_15")
        self.gridLayout_2.addWidget(self.btn_15, 2, 0, 1, 1)
        self.btn_16 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_16.sizePolicy().hasHeightForWidth())
        self.btn_16.setSizePolicy(sizePolicy)
        self.btn_16.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_16.setObjectName("btn_16")
        self.gridLayout_2.addWidget(self.btn_16, 2, 1, 1, 1)
        self.btn_17 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_17.sizePolicy().hasHeightForWidth())
        self.btn_17.setSizePolicy(sizePolicy)
        self.btn_17.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_17.setObjectName("btn_17")
        self.gridLayout_2.addWidget(self.btn_17, 2, 2, 1, 1)
        self.btn_10 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_10.sizePolicy().hasHeightForWidth())
        self.btn_10.setSizePolicy(sizePolicy)
        self.btn_10.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_10.setObjectName("btn_10")
        self.gridLayout_2.addWidget(self.btn_10, 0, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btn_27 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_27.sizePolicy().hasHeightForWidth())
        self.btn_27.setSizePolicy(sizePolicy)
        self.btn_27.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_27.setObjectName("btn_27")
        self.gridLayout_4.addWidget(self.btn_27, 0, 0, 1, 1)
        self.btn_28 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_28.sizePolicy().hasHeightForWidth())
        self.btn_28.setSizePolicy(sizePolicy)
        self.btn_28.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_28.setObjectName("btn_28")
        self.gridLayout_4.addWidget(self.btn_28, 0, 1, 1, 1)
        self.btn_29 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_29.sizePolicy().hasHeightForWidth())
        self.btn_29.setSizePolicy(sizePolicy)
        self.btn_29.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_29.setObjectName("btn_29")
        self.gridLayout_4.addWidget(self.btn_29, 0, 2, 1, 1)
        self.btn_30 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_30.sizePolicy().hasHeightForWidth())
        self.btn_30.setSizePolicy(sizePolicy)
        self.btn_30.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_30.setObjectName("btn_30")
        self.gridLayout_4.addWidget(self.btn_30, 1, 0, 1, 1)
        self.btn_31 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_31.sizePolicy().hasHeightForWidth())
        self.btn_31.setSizePolicy(sizePolicy)
        self.btn_31.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_31.setObjectName("btn_31")
        self.gridLayout_4.addWidget(self.btn_31, 1, 1, 1, 1)
        self.btn_32 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_32.sizePolicy().hasHeightForWidth())
        self.btn_32.setSizePolicy(sizePolicy)
        self.btn_32.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_32.setObjectName("btn_32")
        self.gridLayout_4.addWidget(self.btn_32, 1, 2, 1, 1)
        self.btn_33 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_33.sizePolicy().hasHeightForWidth())
        self.btn_33.setSizePolicy(sizePolicy)
        self.btn_33.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_33.setObjectName("btn_33")
        self.gridLayout_4.addWidget(self.btn_33, 2, 0, 1, 1)
        self.btn_34 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_34.sizePolicy().hasHeightForWidth())
        self.btn_34.setSizePolicy(sizePolicy)
        self.btn_34.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_34.setObjectName("btn_34")
        self.gridLayout_4.addWidget(self.btn_34, 2, 1, 1, 1)
        self.btn_35 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_35.sizePolicy().hasHeightForWidth())
        self.btn_35.setSizePolicy(sizePolicy)
        self.btn_35.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_35.setObjectName("btn_35")
        self.gridLayout_4.addWidget(self.btn_35, 2, 2, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_4, 0, 2, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btn_36 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_36.sizePolicy().hasHeightForWidth())
        self.btn_36.setSizePolicy(sizePolicy)
        self.btn_36.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_36.setObjectName("btn_36")
        self.gridLayout_5.addWidget(self.btn_36, 0, 0, 1, 1)
        self.btn_37 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_37.sizePolicy().hasHeightForWidth())
        self.btn_37.setSizePolicy(sizePolicy)
        self.btn_37.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_37.setObjectName("btn_37")
        self.gridLayout_5.addWidget(self.btn_37, 0, 1, 1, 1)
        self.btn_38 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_38.sizePolicy().hasHeightForWidth())
        self.btn_38.setSizePolicy(sizePolicy)
        self.btn_38.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_38.setObjectName("btn_38")
        self.gridLayout_5.addWidget(self.btn_38, 0, 2, 1, 1)
        self.btn_39 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_39.sizePolicy().hasHeightForWidth())
        self.btn_39.setSizePolicy(sizePolicy)
        self.btn_39.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_39.setObjectName("btn_39")
        self.gridLayout_5.addWidget(self.btn_39, 1, 0, 1, 1)
        self.btn_40 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_40.sizePolicy().hasHeightForWidth())
        self.btn_40.setSizePolicy(sizePolicy)
        self.btn_40.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_40.setObjectName("btn_40")
        self.gridLayout_5.addWidget(self.btn_40, 1, 1, 1, 1)
        self.btn_41 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_41.sizePolicy().hasHeightForWidth())
        self.btn_41.setSizePolicy(sizePolicy)
        self.btn_41.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_41.setObjectName("btn_41")
        self.gridLayout_5.addWidget(self.btn_41, 1, 2, 1, 1)
        self.btn_42 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_42.sizePolicy().hasHeightForWidth())
        self.btn_42.setSizePolicy(sizePolicy)
        self.btn_42.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_42.setObjectName("btn_42")
        self.gridLayout_5.addWidget(self.btn_42, 2, 0, 1, 1)
        self.btn_43 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_43.sizePolicy().hasHeightForWidth())
        self.btn_43.setSizePolicy(sizePolicy)
        self.btn_43.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_43.setObjectName("btn_43")
        self.gridLayout_5.addWidget(self.btn_43, 2, 1, 1, 1)
        self.btn_44 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_44.sizePolicy().hasHeightForWidth())
        self.btn_44.setSizePolicy(sizePolicy)
        self.btn_44.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_44.setObjectName("btn_44")
        self.gridLayout_5.addWidget(self.btn_44, 2, 2, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSpacing(1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.btn_45 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_45.sizePolicy().hasHeightForWidth())
        self.btn_45.setSizePolicy(sizePolicy)
        self.btn_45.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_45.setObjectName("btn_45")
        self.gridLayout_6.addWidget(self.btn_45, 0, 0, 1, 1)
        self.btn_46 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_46.sizePolicy().hasHeightForWidth())
        self.btn_46.setSizePolicy(sizePolicy)
        self.btn_46.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_46.setObjectName("btn_46")
        self.gridLayout_6.addWidget(self.btn_46, 0, 1, 1, 1)
        self.btn_47 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_47.sizePolicy().hasHeightForWidth())
        self.btn_47.setSizePolicy(sizePolicy)
        self.btn_47.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_47.setObjectName("btn_47")
        self.gridLayout_6.addWidget(self.btn_47, 0, 2, 1, 1)
        self.btn_48 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_48.sizePolicy().hasHeightForWidth())
        self.btn_48.setSizePolicy(sizePolicy)
        self.btn_48.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_48.setObjectName("btn_48")
        self.gridLayout_6.addWidget(self.btn_48, 1, 0, 1, 1)
        self.btn_49 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_49.sizePolicy().hasHeightForWidth())
        self.btn_49.setSizePolicy(sizePolicy)
        self.btn_49.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_49.setObjectName("btn_49")
        self.gridLayout_6.addWidget(self.btn_49, 1, 1, 1, 1)
        self.btn_50 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_50.sizePolicy().hasHeightForWidth())
        self.btn_50.setSizePolicy(sizePolicy)
        self.btn_50.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_50.setObjectName("btn_50")
        self.gridLayout_6.addWidget(self.btn_50, 1, 2, 1, 1)
        self.btn_51 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_51.sizePolicy().hasHeightForWidth())
        self.btn_51.setSizePolicy(sizePolicy)
        self.btn_51.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_51.setObjectName("btn_51")
        self.gridLayout_6.addWidget(self.btn_51, 2, 0, 1, 1)
        self.btn_52 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_52.sizePolicy().hasHeightForWidth())
        self.btn_52.setSizePolicy(sizePolicy)
        self.btn_52.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_52.setObjectName("btn_52")
        self.gridLayout_6.addWidget(self.btn_52, 2, 1, 1, 1)
        self.btn_53 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_53.sizePolicy().hasHeightForWidth())
        self.btn_53.setSizePolicy(sizePolicy)
        self.btn_53.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_53.setObjectName("btn_53")
        self.gridLayout_6.addWidget(self.btn_53, 2, 2, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_6, 1, 1, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setSpacing(1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.btn_54 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_54.sizePolicy().hasHeightForWidth())
        self.btn_54.setSizePolicy(sizePolicy)
        self.btn_54.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_54.setObjectName("btn_54")
        self.gridLayout_7.addWidget(self.btn_54, 0, 0, 1, 1)
        self.btn_55 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_55.sizePolicy().hasHeightForWidth())
        self.btn_55.setSizePolicy(sizePolicy)
        self.btn_55.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_55.setObjectName("btn_55")
        self.gridLayout_7.addWidget(self.btn_55, 0, 1, 1, 1)
        self.btn_56 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_56.sizePolicy().hasHeightForWidth())
        self.btn_56.setSizePolicy(sizePolicy)
        self.btn_56.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_56.setObjectName("btn_56")
        self.gridLayout_7.addWidget(self.btn_56, 0, 2, 1, 1)
        self.btn_57 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_57.sizePolicy().hasHeightForWidth())
        self.btn_57.setSizePolicy(sizePolicy)
        self.btn_57.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_57.setObjectName("btn_57")
        self.gridLayout_7.addWidget(self.btn_57, 1, 0, 1, 1)
        self.btn_58 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_58.sizePolicy().hasHeightForWidth())
        self.btn_58.setSizePolicy(sizePolicy)
        self.btn_58.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_58.setObjectName("btn_58")
        self.gridLayout_7.addWidget(self.btn_58, 1, 1, 1, 1)
        self.btn_59 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_59.sizePolicy().hasHeightForWidth())
        self.btn_59.setSizePolicy(sizePolicy)
        self.btn_59.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_59.setObjectName("btn_59")
        self.gridLayout_7.addWidget(self.btn_59, 1, 2, 1, 1)
        self.btn_60 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_60.sizePolicy().hasHeightForWidth())
        self.btn_60.setSizePolicy(sizePolicy)
        self.btn_60.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_60.setObjectName("btn_60")
        self.gridLayout_7.addWidget(self.btn_60, 2, 0, 1, 1)
        self.btn_61 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_61.sizePolicy().hasHeightForWidth())
        self.btn_61.setSizePolicy(sizePolicy)
        self.btn_61.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_61.setObjectName("btn_61")
        self.gridLayout_7.addWidget(self.btn_61, 2, 1, 1, 1)
        self.btn_62 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_62.sizePolicy().hasHeightForWidth())
        self.btn_62.setSizePolicy(sizePolicy)
        self.btn_62.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_62.setObjectName("btn_62")
        self.gridLayout_7.addWidget(self.btn_62, 2, 2, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_7, 1, 2, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setSpacing(1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.btn_63 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_63.sizePolicy().hasHeightForWidth())
        self.btn_63.setSizePolicy(sizePolicy)
        self.btn_63.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_63.setObjectName("btn_63")
        self.gridLayout_8.addWidget(self.btn_63, 0, 0, 1, 1)
        self.btn_64 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_64.sizePolicy().hasHeightForWidth())
        self.btn_64.setSizePolicy(sizePolicy)
        self.btn_64.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_64.setObjectName("btn_64")
        self.gridLayout_8.addWidget(self.btn_64, 0, 1, 1, 1)
        self.btn_65 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_65.sizePolicy().hasHeightForWidth())
        self.btn_65.setSizePolicy(sizePolicy)
        self.btn_65.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_65.setObjectName("btn_65")
        self.gridLayout_8.addWidget(self.btn_65, 0, 2, 1, 1)
        self.btn_66 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_66.sizePolicy().hasHeightForWidth())
        self.btn_66.setSizePolicy(sizePolicy)
        self.btn_66.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_66.setObjectName("btn_66")
        self.gridLayout_8.addWidget(self.btn_66, 1, 0, 1, 1)
        self.btn_67 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_67.sizePolicy().hasHeightForWidth())
        self.btn_67.setSizePolicy(sizePolicy)
        self.btn_67.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_67.setObjectName("btn_67")
        self.gridLayout_8.addWidget(self.btn_67, 1, 1, 1, 1)
        self.btn_68 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_68.sizePolicy().hasHeightForWidth())
        self.btn_68.setSizePolicy(sizePolicy)
        self.btn_68.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_68.setObjectName("btn_68")
        self.gridLayout_8.addWidget(self.btn_68, 1, 2, 1, 1)
        self.btn_69 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_69.sizePolicy().hasHeightForWidth())
        self.btn_69.setSizePolicy(sizePolicy)
        self.btn_69.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_69.setObjectName("btn_69")
        self.gridLayout_8.addWidget(self.btn_69, 2, 0, 1, 1)
        self.btn_70 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_70.sizePolicy().hasHeightForWidth())
        self.btn_70.setSizePolicy(sizePolicy)
        self.btn_70.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_70.setObjectName("btn_70")
        self.gridLayout_8.addWidget(self.btn_70, 2, 1, 1, 1)
        self.btn_71 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_71.sizePolicy().hasHeightForWidth())
        self.btn_71.setSizePolicy(sizePolicy)
        self.btn_71.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_71.setObjectName("btn_71")
        self.gridLayout_8.addWidget(self.btn_71, 2, 2, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_8, 2, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setSpacing(1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.btn_72 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_72.sizePolicy().hasHeightForWidth())
        self.btn_72.setSizePolicy(sizePolicy)
        self.btn_72.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_72.setObjectName("btn_72")
        self.gridLayout_9.addWidget(self.btn_72, 0, 0, 1, 1)
        self.btn_76 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_76.sizePolicy().hasHeightForWidth())
        self.btn_76.setSizePolicy(sizePolicy)
        self.btn_76.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_76.setObjectName("btn_76")
        self.gridLayout_9.addWidget(self.btn_76, 1, 1, 1, 1)
        self.btn_73 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_73.sizePolicy().hasHeightForWidth())
        self.btn_73.setSizePolicy(sizePolicy)
        self.btn_73.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_73.setObjectName("btn_73")
        self.gridLayout_9.addWidget(self.btn_73, 0, 1, 1, 1)
        self.btn_77 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_77.sizePolicy().hasHeightForWidth())
        self.btn_77.setSizePolicy(sizePolicy)
        self.btn_77.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_77.setObjectName("btn_77")
        self.gridLayout_9.addWidget(self.btn_77, 1, 2, 1, 1)
        self.btn_75 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_75.sizePolicy().hasHeightForWidth())
        self.btn_75.setSizePolicy(sizePolicy)
        self.btn_75.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_75.setObjectName("btn_75")
        self.gridLayout_9.addWidget(self.btn_75, 1, 0, 1, 1)
        self.btn_78 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_78.sizePolicy().hasHeightForWidth())
        self.btn_78.setSizePolicy(sizePolicy)
        self.btn_78.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_78.setObjectName("btn_78")
        self.gridLayout_9.addWidget(self.btn_78, 2, 0, 1, 1)
        self.btn_80 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_80.sizePolicy().hasHeightForWidth())
        self.btn_80.setSizePolicy(sizePolicy)
        self.btn_80.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_80.setObjectName("btn_80")
        self.gridLayout_9.addWidget(self.btn_80, 2, 2, 1, 1)
        self.btn_79 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_79.sizePolicy().hasHeightForWidth())
        self.btn_79.setSizePolicy(sizePolicy)
        self.btn_79.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_79.setObjectName("btn_79")
        self.gridLayout_9.addWidget(self.btn_79, 2, 1, 1, 1)
        self.btn_74 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_74.sizePolicy().hasHeightForWidth())
        self.btn_74.setSizePolicy(sizePolicy)
        self.btn_74.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_74.setObjectName("btn_74")
        self.gridLayout_9.addWidget(self.btn_74, 0, 2, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_9, 2, 1, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setSpacing(1)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.btn_81 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_81.sizePolicy().hasHeightForWidth())
        self.btn_81.setSizePolicy(sizePolicy)
        self.btn_81.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_81.setObjectName("btn_81")
        self.gridLayout_10.addWidget(self.btn_81, 0, 0, 1, 1)
        self.btn_82 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_82.sizePolicy().hasHeightForWidth())
        self.btn_82.setSizePolicy(sizePolicy)
        self.btn_82.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_82.setObjectName("btn_82")
        self.gridLayout_10.addWidget(self.btn_82, 0, 1, 1, 1)
        self.btn_83 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_83.sizePolicy().hasHeightForWidth())
        self.btn_83.setSizePolicy(sizePolicy)
        self.btn_83.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_83.setObjectName("btn_83")
        self.gridLayout_10.addWidget(self.btn_83, 0, 2, 1, 1)
        self.btn_84 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_84.sizePolicy().hasHeightForWidth())
        self.btn_84.setSizePolicy(sizePolicy)
        self.btn_84.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_84.setObjectName("btn_84")
        self.gridLayout_10.addWidget(self.btn_84, 1, 0, 1, 1)
        self.btn_85 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_85.sizePolicy().hasHeightForWidth())
        self.btn_85.setSizePolicy(sizePolicy)
        self.btn_85.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_85.setObjectName("btn_85")
        self.gridLayout_10.addWidget(self.btn_85, 1, 1, 1, 1)
        self.btn_86 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_86.sizePolicy().hasHeightForWidth())
        self.btn_86.setSizePolicy(sizePolicy)
        self.btn_86.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_86.setObjectName("btn_86")
        self.gridLayout_10.addWidget(self.btn_86, 1, 2, 1, 1)
        self.btn_87 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_87.sizePolicy().hasHeightForWidth())
        self.btn_87.setSizePolicy(sizePolicy)
        self.btn_87.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_87.setObjectName("btn_87")
        self.gridLayout_10.addWidget(self.btn_87, 2, 0, 1, 1)
        self.btn_88 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_88.sizePolicy().hasHeightForWidth())
        self.btn_88.setSizePolicy(sizePolicy)
        self.btn_88.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_88.setObjectName("btn_88")
        self.gridLayout_10.addWidget(self.btn_88, 2, 1, 1, 1)
        self.btn_89 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_89.sizePolicy().hasHeightForWidth())
        self.btn_89.setSizePolicy(sizePolicy)
        self.btn_89.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_89.setObjectName("btn_89")
        self.gridLayout_10.addWidget(self.btn_89, 2, 2, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 501, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menu)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setAcceptDrops(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_8 = QtWidgets.QAction(MainWindow)
        self.action_8.setObjectName("action_8")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        self.action_10 = QtWidgets.QAction(MainWindow)
        self.action_10.setObjectName("action_10")
        self.menu_2.addAction(self.action_7)
        self.menu_2.addAction(self.action_8)
        self.menu_2.addAction(self.action_9)
        self.menu_2.addAction(self.action_10)
        self.menu.addAction(self.menu_2.menuAction())
        self.menu.addSeparator()
        self.menu.addAction(self.action_5)
        self.menu.addAction(self.action_2)
        self.menu.addSeparator()
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Судоку"))
        self.btn_0.setText(_translate("MainWindow", "PushButton"))
        self.btn_1.setText(_translate("MainWindow", "PushButton"))
        self.btn_2.setText(_translate("MainWindow", "PushButton"))
        self.btn_3.setText(_translate("MainWindow", "PushButton"))
        self.btn_4.setText(_translate("MainWindow", "PushButton"))
        self.btn_5.setText(_translate("MainWindow", "PushButton"))
        self.btn_6.setText(_translate("MainWindow", "PushButton"))
        self.btn_7.setText(_translate("MainWindow", "PushButton"))
        self.btn_8.setText(_translate("MainWindow", "PushButton"))
        self.btn_9.setText(_translate("MainWindow", "PushButton"))
        self.btn_11.setText(_translate("MainWindow", "PushButton"))
        self.btn_12.setText(_translate("MainWindow", "PushButton"))
        self.btn_13.setText(_translate("MainWindow", "PushButton"))
        self.btn_14.setText(_translate("MainWindow", "PushButton"))
        self.btn_15.setText(_translate("MainWindow", "PushButton"))
        self.btn_16.setText(_translate("MainWindow", "PushButton"))
        self.btn_17.setText(_translate("MainWindow", "PushButton"))
        self.btn_10.setText(_translate("MainWindow", "PushButton"))
        self.btn_27.setText(_translate("MainWindow", "PushButton"))
        self.btn_28.setText(_translate("MainWindow", "PushButton"))
        self.btn_29.setText(_translate("MainWindow", "PushButton"))
        self.btn_30.setText(_translate("MainWindow", "PushButton"))
        self.btn_31.setText(_translate("MainWindow", "PushButton"))
        self.btn_32.setText(_translate("MainWindow", "PushButton"))
        self.btn_33.setText(_translate("MainWindow", "PushButton"))
        self.btn_34.setText(_translate("MainWindow", "PushButton"))
        self.btn_35.setText(_translate("MainWindow", "PushButton"))
        self.btn_36.setText(_translate("MainWindow", "PushButton"))
        self.btn_37.setText(_translate("MainWindow", "PushButton"))
        self.btn_38.setText(_translate("MainWindow", "PushButton"))
        self.btn_39.setText(_translate("MainWindow", "PushButton"))
        self.btn_40.setText(_translate("MainWindow", "PushButton"))
        self.btn_41.setText(_translate("MainWindow", "PushButton"))
        self.btn_42.setText(_translate("MainWindow", "PushButton"))
        self.btn_43.setText(_translate("MainWindow", "PushButton"))
        self.btn_44.setText(_translate("MainWindow", "PushButton"))
        self.btn_45.setText(_translate("MainWindow", "PushButton"))
        self.btn_46.setText(_translate("MainWindow", "PushButton"))
        self.btn_47.setText(_translate("MainWindow", "PushButton"))
        self.btn_48.setText(_translate("MainWindow", "PushButton"))
        self.btn_49.setText(_translate("MainWindow", "PushButton"))
        self.btn_50.setText(_translate("MainWindow", "PushButton"))
        self.btn_51.setText(_translate("MainWindow", "PushButton"))
        self.btn_52.setText(_translate("MainWindow", "PushButton"))
        self.btn_53.setText(_translate("MainWindow", "PushButton"))
        self.btn_54.setText(_translate("MainWindow", "PushButton"))
        self.btn_55.setText(_translate("MainWindow", "PushButton"))
        self.btn_56.setText(_translate("MainWindow", "PushButton"))
        self.btn_57.setText(_translate("MainWindow", "PushButton"))
        self.btn_58.setText(_translate("MainWindow", "PushButton"))
        self.btn_59.setText(_translate("MainWindow", "PushButton"))
        self.btn_60.setText(_translate("MainWindow", "PushButton"))
        self.btn_61.setText(_translate("MainWindow", "PushButton"))
        self.btn_62.setText(_translate("MainWindow", "PushButton"))
        self.btn_63.setText(_translate("MainWindow", "PushButton"))
        self.btn_64.setText(_translate("MainWindow", "PushButton"))
        self.btn_65.setText(_translate("MainWindow", "PushButton"))
        self.btn_66.setText(_translate("MainWindow", "PushButton"))
        self.btn_67.setText(_translate("MainWindow", "PushButton"))
        self.btn_68.setText(_translate("MainWindow", "PushButton"))
        self.btn_69.setText(_translate("MainWindow", "PushButton"))
        self.btn_70.setText(_translate("MainWindow", "PushButton"))
        self.btn_71.setText(_translate("MainWindow", "PushButton"))
        self.btn_72.setText(_translate("MainWindow", "PushButton"))
        self.btn_76.setText(_translate("MainWindow", "PushButton"))
        self.btn_73.setText(_translate("MainWindow", "PushButton"))
        self.btn_77.setText(_translate("MainWindow", "PushButton"))
        self.btn_75.setText(_translate("MainWindow", "PushButton"))
        self.btn_78.setText(_translate("MainWindow", "PushButton"))
        self.btn_80.setText(_translate("MainWindow", "PushButton"))
        self.btn_79.setText(_translate("MainWindow", "PushButton"))
        self.btn_74.setText(_translate("MainWindow", "PushButton"))
        self.btn_81.setText(_translate("MainWindow", "PushButton"))
        self.btn_82.setText(_translate("MainWindow", "PushButton"))
        self.btn_83.setText(_translate("MainWindow", "PushButton"))
        self.btn_84.setText(_translate("MainWindow", "PushButton"))
        self.btn_85.setText(_translate("MainWindow", "PushButton"))
        self.btn_86.setText(_translate("MainWindow", "PushButton"))
        self.btn_87.setText(_translate("MainWindow", "PushButton"))
        self.btn_88.setText(_translate("MainWindow", "PushButton"))
        self.btn_89.setText(_translate("MainWindow", "PushButton"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Новая игра"))
        self.action.setText(_translate("MainWindow", "Выход"))
        self.action_2.setText(_translate("MainWindow", "Таблица рекордов"))
        self.action_5.setText(_translate("MainWindow", "Сохранить"))
        self.action_7.setText(_translate("MainWindow", "Легко 👶"))
        self.action_8.setText(_translate("MainWindow", "Средне 👦"))
        self.action_9.setText(_translate("MainWindow", "Сложно 🤓"))
        self.action_10.setText(_translate("MainWindow", "Адски сложно 🎓"))
